### ISSUE TITLE
Upload Result - Tags not created

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#20] opened 2020-08-18 12:24 UTC
## Page: 
Upload Result: https://193.144.46.238/upload

## Issue:
After adding a Tag, it is not displayed on the "Select Tags"
See example
![image](https://user-images.githubusercontent.com/47473455/90512106-ddf12d00-e15d-11ea-8229-d45746370773.png)

## Expected:
After pressing the button "Add Tag" the tag is displayed.

## Notes / Additional:
In case I do a mistake and I add a worng tag, will it be on the display list forever?

**Comment by BorjaEst** [comment] 2020-08-18 12:26
It looks the login time is very short, so probably I was logged out (but the application did not informed me about) so when I was trying to add tags it was not possible. 

I will keep you updated If I find out more.

**Comment by TheChristophe** [comment] 2020-08-20 01:27
Could not reproduce while logged in; I entered a new tagname, pressed Add Tag and the tag stayed, even until after a refresh.

**Comment by TheChristophe** [comment] 2020-08-20 01:29
Regarding
> In case I do a mistake and I add a worng tag, will it be on the display list forever?
It may be reasonable to only add the newly added tags if they were selected for the result? CC: @mlbehr

**Comment by BorjaEst** [comment] 2020-08-20 14:17
I can confirm the issue, note you have to wait a bit until the session expires.
Then you press the buttons and the tags are not added.

The behavior might be normal, but, I would expect that when I press the button Add Tag, if the action did not happen, I would get an alert such (your session expired).

**Comment by vykozlov** [comment] 2020-08-20 18:29
Can't confirm the original issue: when logged, a new tag is added correctly.
Shall we close the issue?

**Comment by TheChristophe** [comment] 2020-08-21 02:42
I will mark this as duplicate of #22, since it is effectively a consequence of not being logged in.

**Comment by TheChristophe** [comment] 2020-08-21 02:42
Duplicate of #22

**Comment by BorjaEst** [comment] 2020-09-14 09:16
Not sure if the changes were affencting this, but the begaviour of tags is a bit strange:
Here, tag1 exists:
![image](https://user-images.githubusercontent.com/47473455/93067372-6e4a6100-f67b-11ea-9990-f9237a5927f7.png)

After reload (F5) tag1 dissapears but a different one which was not before appears:
![image](https://user-images.githubusercontent.com/47473455/93067450-87eba880-f67b-11ea-9511-c2a393c57440.png)

If I reload again:
![image](https://user-images.githubusercontent.com/47473455/93067525-a05bc300-f67b-11ea-88aa-00db7fbb9e12.png)

Another change of tags!
So it seems the list is not really displaying/creating tags.

**Comment by BorjaEst** [comment] 2020-09-14 09:17
> I will mark this as duplicate of #22, since it is effectively a consequence of not being logged in.

Not any more related to previous, so i will remove "duplicate"

**Comment by TheChristophe** [comment] 2020-09-14 09:20
Please do not reuse old issues that have been resolved.
That aside, I've been testing for the past hour; there is a weird persistency problem with SQLAlchemy right now; changes in one worker do not seem to propagate to other workers, which was also affecting some report behaviour. I'm making a new issue for that.

**Comment by BorjaEst** [comment] 2020-09-14 09:20
Ok, I am restoring the previous state of this issue.

**Closed by TheChristophe** 2020-09-14 09:20 UTC

**Comment by TheChristophe** [comment] 2020-09-14 09:24
The new issue has been documented in #44.
